fixing windows download and environment
dz0ny/gobu pull request #3
Opened 2016-09-26 05:31 UTC by m0veax

#2

2016-09-26 07:14 UTC, slax0rr commented on .gitignore
> +#src/*
Why remove 'src/*' and 'gobu' from gitignore?

2016-09-26 07:17 UTC, slax0rr commented on src/gobu/main.go
> +		defaultShell = "cmd.exe" // TODO find parent process name
Getppid() of 'os' package and https://github.com/mitchellh/go-ps might be of help.

2016-09-26 07:17 UTC, slax0rr commented on src/gobu/main.go
> +
Remove trailing whitespace.

2016-09-26 07:18 UTC, slax0rr commented on src/gobu/main.go
> +	extension := "tar.gz"
Use package var to avoid setting in multiple locations, or pass it as input to the 'download' func.

2016-09-26 07:18 UTC, slax0rr commented on src/gobu/remote.go
> +	extension := ".tar.gz"
Read from global var set in the 'main' func, or pass it as input to the this func from 'main'.

2016-09-26 07:19 UTC, slax0rr requested changes
Looking good, needs minor changes.

2016-09-26 07:20 UTC, m0veax commented
thanks for the feedback!

2016-09-28 09:31 UTC, m0veax commented on .gitignore
> +#src/*
otherwise i couldnt check in changes in the source file. i will prove if that it is needed.

2016-09-28 09:37 UTC, m0veax commented on src/gobu/main.go
> +
yeah, installed vim-go, there wouldnt be something like that again :)

2016-09-28 09:57 UTC, m0veax commented on .gitignore
> +#src/*
restored that changes

2016-09-28 11:16 UTC, m0veax commented on src/gobu/main.go
> +		defaultShell = "cmd.exe" // TODO find parent process name
thanks for the advice, i am getting the used parent process per go-ps now and execute it in a windows environment

2016-09-28 11:18 UTC, m0veax commented
I solved the parent process shell spawning now. I am doing some beautifying now and would be glad if my PR would get accepted afterwards :) I'll leave a note after i finished cleaning up

2016-09-28 12:36 UTC, dz0ny reviewed
Looks good :)

2016-09-28 12:36 UTC, dz0ny commented on src/gobu/main.go
> +		shell = exe
You should assign shell directly, no need for other variable.

2016-09-28 12:36 UTC, dz0ny commented on src/gobu/main.go
> +		fmt.Println(parentId)
log.Debug

2016-09-28 12:36 UTC, dz0ny commented on src/gobu/zip.go
> +
use gofmt to remove unneeded newlines

2016-09-28 18:23 UTC, m0veax commented on src/gobu/main.go
> +	extension := "tar.gz"
created package vars with extensions and use them for further processing

2016-09-28 18:23 UTC, m0veax commented on src/gobu/remote.go
> +	extension := ".tar.gz"
extension is now a param for the download method

2016-09-28 18:25 UTC, m0veax commented on src/gobu/main.go
> +		fmt.Println(parentId)
removed, cause not needed. just added for debugging

2016-09-28 18:25 UTC, m0veax commented on src/gobu/main.go
> +		shell = exe
done, thanks

2016-09-28 18:26 UTC, m0veax commented on src/gobu/zip.go
> +
done, thanks for the hint :)

2016-09-28 18:34 UTC, m0veax commented
Hey, many thanks for the feedback and hints.

It was a great first touch with golang!

If you do not found anything further i can modify, i would call that "merge ready".

I've tested:

* downloading and spawning shell in windows 10
* downloading and spawning shell in ubuntu
* environment variables in windows
* environment variables in ubuntu

Cheers,

Patrick

2016-09-28 18:42 UTC, dz0ny commented
@m0veax I can merge right away if don't want to participate in hacktoberfest :)

2016-09-28 20:25 UTC, m0veax commented
oh, wait please, i want to participate indeed!

2016-10-01 09:38 UTC, merged